[template]
dir='.'
file='modeshare_template.xlsx'

[output]
dir='.'
file='modeshare.xlsx'

[taz_to_agg_geo]
file=''
taz_field=''
geo_field=''

[survey]
dir=''
raw_dir=''

[survey.hh]
file='hhfilename.dat'
sep=' '
weight='hhweight'

[survey.person]
file='personfilename.dat'
sep=' '
weight='personweight'

[survey.day]
file='dayfilename.dat'
sep=' '
weight='dayweight'

[survey.trip]
file='tripfilename.dat'
sep=' '
weight='tripweight'

[survey.tour]
file='tourfilename.dat'
sep=' '
weight='tourweight'

[survey.raw_hh]
file='hh.csv'
weight='hh_weight'

[survey.raw_person]
file='person.csv'
weight='person_weight'

[survey.raw_day]
file='day.csv'
weight='day_weight'

[survey.raw_trip]
file='trip.csv'
weight='trip_weight'

[modesums]
[modesums.to_from_within]
ogeo=1
dgeo=1
how='or'

[modesums.to_from]
ogeo=1
dgeo=1
how='xor'

[modesums.within]
ogeo=1
dgeo=1
how='and'


