apc_directory = "Q:/Data/Observed/Transit/Muni/APC/2022/06_Jun"
apc_filenames = [
    "apc_stop_boardings_facts_SFCTA_2022-06.csv"
]
gtfs_stops_GIS_filepath = "Q:/Data/Observed/Transit/Muni/APC/2022/06_Jun/GTFS_stops.shp"
# TODO not sure how to generate this postprocessing file at all,
# thus keep using 2022 one
postprocessing_overlap_pairs_filepath = "Q:/Data/Observed/Transit/Muni/APC/2022/06_Jun/postprocessing_overlapping_transit_segments_2022.csv"
cmp_plus_GIS_filepath = "Q:/CMP/LOS Monitoring 2021/CMP_plus_shp/old_cmp_plus/cmp_segments_plus.shp"
inrix_network_GIS_filepath = "Q:/GIS/Transportation/Roads/INRIX/XD/21_01/maprelease-shapefiles/SF/Inrix_XD_2101_SF_manualedit.shp"
cmp_inrix_network_conflation_filepath = "Q:/CMP/LOS Monitoring 2021/Network_Conflation/CMP_Segment_INRIX_Links_Correspondence_2101_Manual_PLUS_Updated.csv"
output_directory = "Q:/CMP/LOS Monitoring 2023/transit/volume_and_speed/2206"
year = 2022

[cmp_segments]
exempt = [237, 245]