apc_directory = "Q:/Data/Observed/Transit/Muni/APC/2025/parsed"
apc_filenames = ["OrbCAD_dbo_apc_correlated_2025_AprMay.parquet"]
# HOTFIX named -geo.parquet to differentiate it from non-geo parquet
# otherwise reading the geoparquet into polars would throw error
stops_filename = "bus_stops-geo.parquet"
# TODO not sure how to generate this postprocessing file at all,
# thus keep using 2022 one
postprocessing_overlap_pairs_filepath = "Q:/CMP/LOS Monitoring 2025/transit/volume_and_speed/2504-2505/inputs/manual_overlapping_segments.csv"
cmp_plus_GIS_filepath = "Q:/GIS/Transportation/Roads/CMP/cmp_roadway_segments.shp"
inrix_network_GIS_filepath = "Q:/GIS/Transportation/Roads/INRIX/XD/2501/shapefile/INRIX_XD-SF-2501.shp"
cmp_inrix_network_conflation_filepath = "Q:/CMP/LOS Monitoring 2025/Network_Conflation/v2501/CMP_Segment_INRIX_Links_Correspondence_2501_Manual-expandednetwork.csv"
output_directory = "Q:/CMP/LOS Monitoring 2025/transit/volume_and_speed/2504-2505/"
year = 2025

[cmp_segments]
exempt = [237, 245]